[package]
name = "imageloader"
version = "0.1.0"
authors = ["Dmitry Nazarov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
reqwest = "0.9.18"
image = "0.21.2"